// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	traefik_laravel_forge "github.com/Wicked-Sick-Ltd/traefik-laravel-forge"
)

// MockForgeClient is an autogenerated mock type for the ForgeClient type
type MockForgeClient struct {
	mock.Mock
}

type MockForgeClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockForgeClient) EXPECT() *MockForgeClient_Expecter {
	return &MockForgeClient_Expecter{mock: &_m.Mock}
}

// FetchDomains provides a mock function with given fields: serverID, siteID
func (_m *MockForgeClient) FetchDomains(serverID string, siteID string) ([]traefik_laravel_forge.ForgeDomain, error) {
	ret := _m.Called(serverID, siteID)

	if len(ret) == 0 {
		panic("no return value specified for FetchDomains")
	}

	var r0 []traefik_laravel_forge.ForgeDomain
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) ([]traefik_laravel_forge.ForgeDomain, error)); ok {
		return rf(serverID, siteID)
	}
	if rf, ok := ret.Get(0).(func(string, string) []traefik_laravel_forge.ForgeDomain); ok {
		r0 = rf(serverID, siteID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]traefik_laravel_forge.ForgeDomain)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(serverID, siteID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockForgeClient_FetchDomains_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchDomains'
type MockForgeClient_FetchDomains_Call struct {
	*mock.Call
}

// FetchDomains is a helper method to define mock.On call
//   - serverID string
//   - siteID string
func (_e *MockForgeClient_Expecter) FetchDomains(serverID interface{}, siteID interface{}) *MockForgeClient_FetchDomains_Call {
	return &MockForgeClient_FetchDomains_Call{Call: _e.mock.On("FetchDomains", serverID, siteID)}
}

func (_c *MockForgeClient_FetchDomains_Call) Run(run func(serverID string, siteID string)) *MockForgeClient_FetchDomains_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockForgeClient_FetchDomains_Call) Return(_a0 []traefik_laravel_forge.ForgeDomain, _a1 error) *MockForgeClient_FetchDomains_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockForgeClient_FetchDomains_Call) RunAndReturn(run func(string, string) ([]traefik_laravel_forge.ForgeDomain, error)) *MockForgeClient_FetchDomains_Call {
	_c.Call.Return(run)
	return _c
}

// FetchReverbIntegration provides a mock function with given fields: serverID, siteID
func (_m *MockForgeClient) FetchReverbIntegration(serverID string, siteID string) (*traefik_laravel_forge.ForgeReverbIntegration, error) {
	ret := _m.Called(serverID, siteID)

	if len(ret) == 0 {
		panic("no return value specified for FetchReverbIntegration")
	}

	var r0 *traefik_laravel_forge.ForgeReverbIntegration
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*traefik_laravel_forge.ForgeReverbIntegration, error)); ok {
		return rf(serverID, siteID)
	}
	if rf, ok := ret.Get(0).(func(string, string) *traefik_laravel_forge.ForgeReverbIntegration); ok {
		r0 = rf(serverID, siteID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*traefik_laravel_forge.ForgeReverbIntegration)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(serverID, siteID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockForgeClient_FetchReverbIntegration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchReverbIntegration'
type MockForgeClient_FetchReverbIntegration_Call struct {
	*mock.Call
}

// FetchReverbIntegration is a helper method to define mock.On call
//   - serverID string
//   - siteID string
func (_e *MockForgeClient_Expecter) FetchReverbIntegration(serverID interface{}, siteID interface{}) *MockForgeClient_FetchReverbIntegration_Call {
	return &MockForgeClient_FetchReverbIntegration_Call{Call: _e.mock.On("FetchReverbIntegration", serverID, siteID)}
}

func (_c *MockForgeClient_FetchReverbIntegration_Call) Run(run func(serverID string, siteID string)) *MockForgeClient_FetchReverbIntegration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockForgeClient_FetchReverbIntegration_Call) Return(_a0 *traefik_laravel_forge.ForgeReverbIntegration, _a1 error) *MockForgeClient_FetchReverbIntegration_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockForgeClient_FetchReverbIntegration_Call) RunAndReturn(run func(string, string) (*traefik_laravel_forge.ForgeReverbIntegration, error)) *MockForgeClient_FetchReverbIntegration_Call {
	_c.Call.Return(run)
	return _c
}

// FetchServers provides a mock function with no fields
func (_m *MockForgeClient) FetchServers() ([]traefik_laravel_forge.ForgeServer, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FetchServers")
	}

	var r0 []traefik_laravel_forge.ForgeServer
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]traefik_laravel_forge.ForgeServer, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []traefik_laravel_forge.ForgeServer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]traefik_laravel_forge.ForgeServer)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockForgeClient_FetchServers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchServers'
type MockForgeClient_FetchServers_Call struct {
	*mock.Call
}

// FetchServers is a helper method to define mock.On call
func (_e *MockForgeClient_Expecter) FetchServers() *MockForgeClient_FetchServers_Call {
	return &MockForgeClient_FetchServers_Call{Call: _e.mock.On("FetchServers")}
}

func (_c *MockForgeClient_FetchServers_Call) Run(run func()) *MockForgeClient_FetchServers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockForgeClient_FetchServers_Call) Return(_a0 []traefik_laravel_forge.ForgeServer, _a1 error) *MockForgeClient_FetchServers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockForgeClient_FetchServers_Call) RunAndReturn(run func() ([]traefik_laravel_forge.ForgeServer, error)) *MockForgeClient_FetchServers_Call {
	_c.Call.Return(run)
	return _c
}

// FetchSites provides a mock function with given fields: serverID
func (_m *MockForgeClient) FetchSites(serverID string) ([]traefik_laravel_forge.ForgeSite, error) {
	ret := _m.Called(serverID)

	if len(ret) == 0 {
		panic("no return value specified for FetchSites")
	}

	var r0 []traefik_laravel_forge.ForgeSite
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]traefik_laravel_forge.ForgeSite, error)); ok {
		return rf(serverID)
	}
	if rf, ok := ret.Get(0).(func(string) []traefik_laravel_forge.ForgeSite); ok {
		r0 = rf(serverID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]traefik_laravel_forge.ForgeSite)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(serverID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockForgeClient_FetchSites_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchSites'
type MockForgeClient_FetchSites_Call struct {
	*mock.Call
}

// FetchSites is a helper method to define mock.On call
//   - serverID string
func (_e *MockForgeClient_Expecter) FetchSites(serverID interface{}) *MockForgeClient_FetchSites_Call {
	return &MockForgeClient_FetchSites_Call{Call: _e.mock.On("FetchSites", serverID)}
}

func (_c *MockForgeClient_FetchSites_Call) Run(run func(serverID string)) *MockForgeClient_FetchSites_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockForgeClient_FetchSites_Call) Return(_a0 []traefik_laravel_forge.ForgeSite, _a1 error) *MockForgeClient_FetchSites_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockForgeClient_FetchSites_Call) RunAndReturn(run func(string) ([]traefik_laravel_forge.ForgeSite, error)) *MockForgeClient_FetchSites_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockForgeClient creates a new instance of MockForgeClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockForgeClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockForgeClient {
	mock := &MockForgeClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
